# title: "Blog của Nguyễn Năng Anh"
description: "Blog cá nhân trên GitHub Pages với Jekyll"
theme: minima

# Cấu hình các trang tùy chỉnh
paginate: 5 # Số bài viết mỗi trang

# Cấu hình tác giả và các liên kết mạng xã hội
author:
  name: "Nguyễn Năng Anh"
  links:
    - label: "Facebook"
      url: "https://www.facebook.com/profile.php?id=100035191161128&mibextid=LQQJ4d" # Thay bằng tên người dùng Facebook của bạn
    - label: "Instagram"
      url: "https://www.instagram.com/nguyennanganh_ig" # Thay bằng tên người dùng Instagram của bạn
    - label: "GitHub"
      url: "https://github.com/nguyennanganh" # Đường dẫn GitHub của bạn

# Thông tin cấu hình bài đăng
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year-:month-:day/:title/
